# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "async-limiter-1.0.1" = {
      name = "async-limiter";
      packageName = "async-limiter";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-limiter/-/async-limiter-1.0.1.tgz";
        sha512 = "csOlWGAcRFJaI6m+F2WKdnMKr4HhdhFVBk0H/QbJFMCr+uO2kwohwXQPxw/9OCxp05r5ghVBFSyioixx3gfkNQ==";
      };
    };
    "discord-rpc-3.1.1" = {
      name = "discord-rpc";
      packageName = "discord-rpc";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/discord-rpc/-/discord-rpc-3.1.1.tgz";
        sha512 = "2nTB+82q4OnCtataJkWMQ2YBWs2UEjs490uC7/xSTvXAOb7I+ZDsweHWFL692sSpDzg7pRlmy1+XVyjWqleulg==";
      };
    };
    "electron-is-dev-1.2.0" = {
      name = "electron-is-dev";
      packageName = "electron-is-dev";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-is-dev/-/electron-is-dev-1.2.0.tgz";
        sha512 = "R1oD5gMBPS7PVU8gJwH6CtT0e6VSoD0+SzSnYpNm+dBkcijgA+K7VAMHDfnRq/lkKPZArpzplTW6jfiMYosdzw==";
      };
    };
    "jquery-3.5.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.5.1.tgz";
        sha512 = "XwIBPqcMn57FxfT+Go5pzySnm4KWkT1Tv7gjrpT1srtf8Weynl6R273VJ5GjkRb51IzMp5nbaPjJXMWeju2MKg==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json5-2.1.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.1.3.tgz";
        sha512 = "KXPvOm8K9IJKFM0bmdn8QXh7udDh1g/giieX0NLCaMnb4hEiVFqnop2ImTXCc5e0/oHz3LTqmHGtExn5hfMkOA==";
      };
    };
    "linkifyjs-2.1.9" = {
      name = "linkifyjs";
      packageName = "linkifyjs";
      version = "2.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkifyjs/-/linkifyjs-2.1.9.tgz";
        sha512 = "74ivurkK6WHvHFozVaGtQWV38FzBwSTGNmJolEgFp7QgR2bl6ArUWlvT4GcHKbPe1z3nWYi+VUdDZk16zDOVug==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "node-fetch-2.6.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.0.tgz";
        sha512 = "8dG4H5ujfvFiqDmVu9fQ5bOHUC15JMjMY/Zumv26oOvvVJjM67KF8koCWIabKQ1GJIa9r2mMZscBq/TbdOcmNA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "pako-1.0.10" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.10.tgz";
        sha512 = "0DTvPVU3ed8+HNXOu5Bs+o//Mbdj9VNQMUOe9oKCwh8l0GNwpTDMKCWbRjgtD291AWnkAgkqA/LOnQS8AmS1tw==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-16.13.1" = {
      name = "react";
      packageName = "react";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.13.1.tgz";
        sha512 = "YMZQQq32xHLX0bz5Mnibv1/LHb3Sqzngu7xstSM+vrkE5Kzr9xE0yMByK5kMoTK30YVJE61WfbxIFFvfeDKT1w==";
      };
    };
    "react-dom-16.13.1" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz";
        sha512 = "81PIMmVLnCNLO/fFOQxdQkvEq/+Hfpv24XNJfpyZhTRfO0QcmQIF/PgCa1zCOj2w1hrn12MFLyaJ/G0+Mxtfag==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "scheduler-0.19.1" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz";
        sha512 = "n/zwRWRYSUj0/3g/otKDRPMh6qv2SYMWNq85IEa8iZyAv8od9zDYpGSnpBEjNgcMNq6Scbu5KfIPxNF72R/2EA==";
      };
    };
    "upng-js-2.1.0" = {
      name = "upng-js";
      packageName = "upng-js";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/upng-js/-/upng-js-2.1.0.tgz";
        sha512 = "d3xzZzpMP64YkjP5pr8gNyvBt7dLk/uGI67EctzDuVp4lCZyVMo0aJO6l/VDlgbInJYDY6cnClLoBp29eKWI6g==";
      };
    };
    "ws-7.1.2" = {
      name = "ws";
      packageName = "ws";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.1.2.tgz";
        sha512 = "gftXq3XI81cJCgkUiAVixA0raD9IVmXqsylCrjRygw4+UOOGzPoxnQ6r/CnVL9i+mDncJo94tSkyrtuuQVBmrg==";
      };
    };
    "ws-7.3.0" = {
      name = "ws";
      packageName = "ws";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.3.0.tgz";
        sha512 = "iFtXzngZVXPGgpTlP1rBqsUK82p9tKqsWRPg5L56egiljujJT3vGAYnHANvFxBieXrTFavhzhxW52jnaWV+w2w==";
      };
    };
  };
  args = {
    name = "moebius";
    packageName = "moebius";
    version = "1.0.29";
    src = ./.;
    dependencies = [
      sources."async-limiter-1.0.1"
      (sources."discord-rpc-3.1.1" // {
        dependencies = [
          sources."ws-7.1.2"
        ];
      })
      sources."electron-is-dev-1.2.0"
      sources."jquery-3.5.1"
      sources."js-tokens-4.0.0"
      sources."json5-2.1.3"
      sources."linkifyjs-2.1.9"
      sources."loose-envify-1.4.0"
      sources."minimist-1.2.5"
      sources."node-fetch-2.6.0"
      sources."object-assign-4.1.1"
      sources."pako-1.0.10"
      sources."prop-types-15.7.2"
      sources."react-16.13.1"
      sources."react-dom-16.13.1"
      sources."react-is-16.13.1"
      sources."scheduler-0.19.1"
      sources."upng-js-2.1.0"
      sources."ws-7.3.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Modern ANSI Art Editor";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
